name: CI Build for Docker Action 
on:
  workflow_dispatch:
        
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
    
      - name: Run my own container action
        id: hello-action
        uses: .
        with:
          who-to-greet: '@andreas-borglin'
          
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
